name: Slack IMAPLIB
on:
  push:
    branches:
      - main

  schedule:
    # https://crontab.guru/
    # Past 1 hour day-of-week (Monday through Friday)
    - cron: '0 */1 * * 1-5'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout & Set Environment Variables
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' 

      - name: Set up environment variables
        run: |
          cd $GITHUB_WORKSPACE
          echo "IMAP4_SSL=${{ secrets.IMAP4_SSL }}" >> .env
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "LABEL=${{ secrets.LABEL }}" >> .env
          pip install -r requirements.txt 
          python3 main.py >> email.txt
          echo "email="$(cat email.txt)"" > $GITHUB_ENV
          echo $email

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
        # For posting a rich message using Block Kit
          payload: |
            {
              "text": "Unread Email",
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*user name*\n Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*email*" 
                    },
                    {
                      "type": "mrkdwn",
                      "text": ${{ env.email }}
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
